<?php
/**
 * Implements hook_theme().
 */
function gbls_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'gbls_form_embed' => array(
      'variables' => [
        'poverty_base' => NULL,
        'poverty_increment' => NULL,
        'checker_title' => NULL,
        'checker_description' => NULL,
        'checker_qualifies' => NULL,
        'checker_disqualifies' => NULL,
        'rules_url' => NULL,
        'coverage_zips' => NULL,
      ],
    ),
  );
}